// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAovqpGPZuAjjBDNtyGuLtoOryI2AVA3u8',
    appId: '1:492471411308:android:7782a40c72934bace92e49',
    messagingSenderId: '492471411308',
    projectId: 'velvetand-iron-training-mhr8qv',
    storageBucket: 'velvetand-iron-training-mhr8qv.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBc8sLdZ-jI_-Ainz_7lBGl0VdYvSUvuIU',
    appId: '1:492471411308:ios:fce36d4291c65235e92e49',
    messagingSenderId: '492471411308',
    projectId: 'velvetand-iron-training-mhr8qv',
    storageBucket: 'velvetand-iron-training-mhr8qv.firebasestorage.app',
    androidClientId: '492471411308-9tlv6ic6fb9im8k81hu2vqtnku69jlle.apps.googleusercontent.com',
    iosClientId: '492471411308-3ejvn2ceighl6e215kqojlni97i4hn35.apps.googleusercontent.com',
    iosBundleId: 'com.velvet.velvetiron',
  );

}